[package]
name = "kvs"
version = "0.1.0"
authors = ["Thayumanavar SV <thayumk@gmail.com>"]
description = "A key-value Store"
edition = "2024"

[dependencies]
clap = "4.5.47"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
